/*
Copyright 2021 Kong, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	konnectv1alpha1 "github.com/kong/kubernetes-configuration/api/konnect/v1alpha1"
	scheme "github.com/kong/kubernetes-configuration/pkg/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// KonnectNetworksGetter has a method to return a KonnectNetworkInterface.
// A group's client should implement this interface.
type KonnectNetworksGetter interface {
	KonnectNetworks(namespace string) KonnectNetworkInterface
}

// KonnectNetworkInterface has methods to work with KonnectNetwork resources.
type KonnectNetworkInterface interface {
	Create(ctx context.Context, konnectNetwork *konnectv1alpha1.KonnectNetwork, opts v1.CreateOptions) (*konnectv1alpha1.KonnectNetwork, error)
	Update(ctx context.Context, konnectNetwork *konnectv1alpha1.KonnectNetwork, opts v1.UpdateOptions) (*konnectv1alpha1.KonnectNetwork, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, konnectNetwork *konnectv1alpha1.KonnectNetwork, opts v1.UpdateOptions) (*konnectv1alpha1.KonnectNetwork, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*konnectv1alpha1.KonnectNetwork, error)
	List(ctx context.Context, opts v1.ListOptions) (*konnectv1alpha1.KonnectNetworkList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *konnectv1alpha1.KonnectNetwork, err error)
	KonnectNetworkExpansion
}

// konnectNetworks implements KonnectNetworkInterface
type konnectNetworks struct {
	*gentype.ClientWithList[*konnectv1alpha1.KonnectNetwork, *konnectv1alpha1.KonnectNetworkList]
}

// newKonnectNetworks returns a KonnectNetworks
func newKonnectNetworks(c *KonnectV1alpha1Client, namespace string) *konnectNetworks {
	return &konnectNetworks{
		gentype.NewClientWithList[*konnectv1alpha1.KonnectNetwork, *konnectv1alpha1.KonnectNetworkList](
			"konnectnetworks",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *konnectv1alpha1.KonnectNetwork { return &konnectv1alpha1.KonnectNetwork{} },
			func() *konnectv1alpha1.KonnectNetworkList { return &konnectv1alpha1.KonnectNetworkList{} },
		),
	}
}
