# renovate: datasource=github-releases depName=golangci/golangci-lint
version: v2.8.0
name: golangci-kube-api-linter
destination: ./bin
plugins:
- module: 'sigs.k8s.io/kube-api-linter'
  version: 470c3a315f3ae8281f873d979092ece824d3dcfd
