# renovate: datasource=github-releases depName=golangci/golangci-lint
version: v2.3.0
name: golangci-kube-api-linter
destination: ./bin
plugins:
- module: 'sigs.k8s.io/kube-api-linter'
  version: e719da12d8403e66335882c7ad704f8e95927ce0
