# renovate: datasource=github-releases depName=golangci/golangci-lint
version: v2.1.6
name: golangci-kube-api-linter
destination: ./bin
plugins:
- module: 'sigs.k8s.io/kube-api-linter'
  # This version will not get auto updated so ideally we'd add a renovate
  # config to update this file automatically.
  version: 55d257d89b6570c9870dc29beabaafd97ea607cb
