# renovate: datasource=github-releases depName=golangci/golangci-lint
version: v2.3.0
name: golangci-kube-api-linter
destination: ./bin
plugins:
- module: 'sigs.k8s.io/kube-api-linter'
  version: 1b29e82a0f55f5e1d4bc49c4bfc3e40c944a0200
