# renovate: datasource=github-releases depName=golangci/golangci-lint
version: v2.8.0
name: golangci-kube-api-linter
destination: ./bin
plugins:
- module: 'sigs.k8s.io/kube-api-linter'
  version: ec17fa1c27133c099455df2e2634c2d61407869e
