# renovate: datasource=github-releases depName=golangci/golangci-lint
version: v2.8.0
name: golangci-kube-api-linter
destination: ./bin
plugins:
- module: 'sigs.k8s.io/kube-api-linter'
  version: 39e3d06a2850e38a8e9e82918bab14ce84e608de
