# renovate: datasource=github-releases depName=golangci/golangci-lint
version: v2.4.0
name: golangci-kube-api-linter
destination: ./bin
plugins:
- module: 'sigs.k8s.io/kube-api-linter'
  version: 502783c08f9db0a94a45f4cae1b0bd53a6ee3642
