version: "2"
linters:
  default: none
  enable:
    - kubeapilinter
  settings:
    custom:
      kubeapilinter:
        type: module
        description: Kube API LInter lints Kube like APIs based on API conventions and best practices.
        settings:
          linters:
            disable:
              - "*"
            enable:
              # Konnect related fields have underscores in their names, which
              # is not recommended and yields errors with jsontags linter.
              # - jsontags
              - duplicatemarkers
              # - maxlength
              - nofloats
              - nomaps
              - nophase
              # - optionalorrequired
              - requiredfields
              - statusoptional
              - statussubresource
          lintersConfig:
            conditions:
              isFirstField: Warn
              useProtobuf: Warn
              usePatchStrategy: Warn
