# renovate: datasource=github-tags depName=kubernetes/code-generator
kube-code-generator: "0.34.1"
# renovate: datasource=github-releases depName=kubernetes-sigs/controller-tools
controller-tools: "0.19.0"
# renovate: datasource=github-releases depName=kubernetes-sigs/kustomize
kustomize: "5.8.0"
# renovate: datasource=github-releases depName=elastic/crd-ref-docs
crd-ref-docs: "0.2.0"
# renovate: datasource=github-releases depName=mikefarah/yq
yq: "4.47.2"
# renovate: datasource=github-releases depName=gotestyourself/gotestsum
gotestsum: "1.12.3"
# renovate: datasource=github-releases depName=golangci/golangci-lint
golangci-lint: "2.8.0"
# renovate: datasource=github-releases depName=rhysd/actionlint
actionlint: "1.7.7"
# renovate: datasource=github-releases depName=koalaman/shellcheck
shellcheck: "0.11.0"
# renovate: datasource=github-tags depName=DavidAnson/markdownlint-cli2
markdownlint-cli2: "0.18.1"
