# renovate: datasource=github-tags depName=kubernetes/code-generator
kube-code-generator: "0.31.2"
# renovate: datasource=github-releases depName=kubernetes-sigs/controller-tools
controller-tools: "0.16.5"
# renovate: datasource=github-releases depName=kubernetes-sigs/kustomize
kustomize: "5.3.0"
# renovate: datasource=github-releases depName=elastic/crd-ref-docs
crd-ref-docs: "0.1.0"
# renovate: datasource=github-releases depName=mikefarah/yq
yq: "4.44.3"
# renovate: datasource=github-releases depName=gotestyourself/gotestsum
gotestsum: "1.12.0"
# renovate: datasource=github-releases depName=golangci/golangci-lint
golangci-lint: "1.62.0"
