# renovate: datasource=github-tags depName=kubernetes/code-generator
kube-code-generator: "0.30.2"
# renovate: datasource=github-releases depName=kubernetes-sigs/controller-tools
controller-tools: "0.15.0"
# renovate: datasource=github-releases depName=kubernetes-sigs/kustomize
kustomize: "5.3.0"
# renovate: datasource=github-releases depName=elastic/crd-ref-docs
crd-ref-docs: "0.0.12"
# renovate: datasource=github-releases depName=mikefarah/yq
yq: "4.44.2"
