/*
Copyright 2021 Kong, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	configurationv1alpha1 "github.com/kong/kubernetes-configuration/v2/api/configuration/v1alpha1"
)

// ControllerReferenceApplyConfiguration represents a declarative configuration of the ControllerReference type for use
// with apply.
type ControllerReferenceApplyConfiguration struct {
	Group     *configurationv1alpha1.Group      `json:"group,omitempty"`
	Kind      *configurationv1alpha1.Kind       `json:"kind,omitempty"`
	Namespace *configurationv1alpha1.Namespace  `json:"namespace,omitempty"`
	Name      *configurationv1alpha1.ObjectName `json:"name,omitempty"`
}

// ControllerReferenceApplyConfiguration constructs a declarative configuration of the ControllerReference type for use with
// apply.
func ControllerReference() *ControllerReferenceApplyConfiguration {
	return &ControllerReferenceApplyConfiguration{}
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *ControllerReferenceApplyConfiguration) WithGroup(value configurationv1alpha1.Group) *ControllerReferenceApplyConfiguration {
	b.Group = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ControllerReferenceApplyConfiguration) WithKind(value configurationv1alpha1.Kind) *ControllerReferenceApplyConfiguration {
	b.Kind = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ControllerReferenceApplyConfiguration) WithNamespace(value configurationv1alpha1.Namespace) *ControllerReferenceApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ControllerReferenceApplyConfiguration) WithName(value configurationv1alpha1.ObjectName) *ControllerReferenceApplyConfiguration {
	b.Name = &value
	return b
}
