/*
Copyright 2021 Kong, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// IngressClassParametersSpecApplyConfiguration represents a declarative configuration of the IngressClassParametersSpec type for use
// with apply.
type IngressClassParametersSpecApplyConfiguration struct {
	ServiceUpstream            *bool `json:"serviceUpstream,omitempty"`
	EnableLegacyRegexDetection *bool `json:"enableLegacyRegexDetection,omitempty"`
}

// IngressClassParametersSpecApplyConfiguration constructs a declarative configuration of the IngressClassParametersSpec type for use with
// apply.
func IngressClassParametersSpec() *IngressClassParametersSpecApplyConfiguration {
	return &IngressClassParametersSpecApplyConfiguration{}
}

// WithServiceUpstream sets the ServiceUpstream field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceUpstream field is set to the value of the last call.
func (b *IngressClassParametersSpecApplyConfiguration) WithServiceUpstream(value bool) *IngressClassParametersSpecApplyConfiguration {
	b.ServiceUpstream = &value
	return b
}

// WithEnableLegacyRegexDetection sets the EnableLegacyRegexDetection field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnableLegacyRegexDetection field is set to the value of the last call.
func (b *IngressClassParametersSpecApplyConfiguration) WithEnableLegacyRegexDetection(value bool) *IngressClassParametersSpecApplyConfiguration {
	b.EnableLegacyRegexDetection = &value
	return b
}
