/*
Copyright 2021 Kong, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/kong/kubernetes-configuration/v2/api/common/v1alpha1"
)

// KongDataPlaneClientCertificateSpecApplyConfiguration represents a declarative configuration of the KongDataPlaneClientCertificateSpec type for use
// with apply.
type KongDataPlaneClientCertificateSpecApplyConfiguration struct {
	ControlPlaneRef                                         *commonv1alpha1.ControlPlaneRef `json:"controlPlaneRef,omitempty"`
	KongDataPlaneClientCertificateAPISpecApplyConfiguration `json:",inline"`
}

// KongDataPlaneClientCertificateSpecApplyConfiguration constructs a declarative configuration of the KongDataPlaneClientCertificateSpec type for use with
// apply.
func KongDataPlaneClientCertificateSpec() *KongDataPlaneClientCertificateSpecApplyConfiguration {
	return &KongDataPlaneClientCertificateSpecApplyConfiguration{}
}

// WithControlPlaneRef sets the ControlPlaneRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ControlPlaneRef field is set to the value of the last call.
func (b *KongDataPlaneClientCertificateSpecApplyConfiguration) WithControlPlaneRef(value commonv1alpha1.ControlPlaneRef) *KongDataPlaneClientCertificateSpecApplyConfiguration {
	b.ControlPlaneRef = &value
	return b
}

// WithCert sets the Cert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cert field is set to the value of the last call.
func (b *KongDataPlaneClientCertificateSpecApplyConfiguration) WithCert(value string) *KongDataPlaneClientCertificateSpecApplyConfiguration {
	b.KongDataPlaneClientCertificateAPISpecApplyConfiguration.Cert = &value
	return b
}
