/*
Copyright 2021 Kong, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	components "github.com/Kong/sdk-konnect-go/models/components"
	commonv1alpha1 "github.com/kong/kubernetes-configuration/v2/api/common/v1alpha1"
)

// KongServiceSpecApplyConfiguration represents a declarative configuration of the KongServiceSpec type for use
// with apply.
type KongServiceSpecApplyConfiguration struct {
	ControlPlaneRef                      *commonv1alpha1.ControlPlaneRef `json:"controlPlaneRef,omitempty"`
	KongServiceAPISpecApplyConfiguration `json:",inline"`
}

// KongServiceSpecApplyConfiguration constructs a declarative configuration of the KongServiceSpec type for use with
// apply.
func KongServiceSpec() *KongServiceSpecApplyConfiguration {
	return &KongServiceSpecApplyConfiguration{}
}

// WithControlPlaneRef sets the ControlPlaneRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ControlPlaneRef field is set to the value of the last call.
func (b *KongServiceSpecApplyConfiguration) WithControlPlaneRef(value commonv1alpha1.ControlPlaneRef) *KongServiceSpecApplyConfiguration {
	b.ControlPlaneRef = &value
	return b
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *KongServiceSpecApplyConfiguration) WithURL(value string) *KongServiceSpecApplyConfiguration {
	b.KongServiceAPISpecApplyConfiguration.URL = &value
	return b
}

// WithConnectTimeout sets the ConnectTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConnectTimeout field is set to the value of the last call.
func (b *KongServiceSpecApplyConfiguration) WithConnectTimeout(value int64) *KongServiceSpecApplyConfiguration {
	b.KongServiceAPISpecApplyConfiguration.ConnectTimeout = &value
	return b
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *KongServiceSpecApplyConfiguration) WithEnabled(value bool) *KongServiceSpecApplyConfiguration {
	b.KongServiceAPISpecApplyConfiguration.Enabled = &value
	return b
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *KongServiceSpecApplyConfiguration) WithHost(value string) *KongServiceSpecApplyConfiguration {
	b.KongServiceAPISpecApplyConfiguration.Host = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *KongServiceSpecApplyConfiguration) WithName(value string) *KongServiceSpecApplyConfiguration {
	b.KongServiceAPISpecApplyConfiguration.Name = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *KongServiceSpecApplyConfiguration) WithPath(value string) *KongServiceSpecApplyConfiguration {
	b.KongServiceAPISpecApplyConfiguration.Path = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *KongServiceSpecApplyConfiguration) WithPort(value int64) *KongServiceSpecApplyConfiguration {
	b.KongServiceAPISpecApplyConfiguration.Port = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *KongServiceSpecApplyConfiguration) WithProtocol(value components.Protocol) *KongServiceSpecApplyConfiguration {
	b.KongServiceAPISpecApplyConfiguration.Protocol = &value
	return b
}

// WithReadTimeout sets the ReadTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadTimeout field is set to the value of the last call.
func (b *KongServiceSpecApplyConfiguration) WithReadTimeout(value int64) *KongServiceSpecApplyConfiguration {
	b.KongServiceAPISpecApplyConfiguration.ReadTimeout = &value
	return b
}

// WithRetries sets the Retries field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Retries field is set to the value of the last call.
func (b *KongServiceSpecApplyConfiguration) WithRetries(value int64) *KongServiceSpecApplyConfiguration {
	b.KongServiceAPISpecApplyConfiguration.Retries = &value
	return b
}

// WithTags sets the Tags field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tags field is set to the value of the last call.
func (b *KongServiceSpecApplyConfiguration) WithTags(value commonv1alpha1.Tags) *KongServiceSpecApplyConfiguration {
	b.KongServiceAPISpecApplyConfiguration.Tags = &value
	return b
}

// WithTLSVerify sets the TLSVerify field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLSVerify field is set to the value of the last call.
func (b *KongServiceSpecApplyConfiguration) WithTLSVerify(value bool) *KongServiceSpecApplyConfiguration {
	b.KongServiceAPISpecApplyConfiguration.TLSVerify = &value
	return b
}

// WithTLSVerifyDepth sets the TLSVerifyDepth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLSVerifyDepth field is set to the value of the last call.
func (b *KongServiceSpecApplyConfiguration) WithTLSVerifyDepth(value int64) *KongServiceSpecApplyConfiguration {
	b.KongServiceAPISpecApplyConfiguration.TLSVerifyDepth = &value
	return b
}

// WithWriteTimeout sets the WriteTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WriteTimeout field is set to the value of the last call.
func (b *KongServiceSpecApplyConfiguration) WithWriteTimeout(value int64) *KongServiceSpecApplyConfiguration {
	b.KongServiceAPISpecApplyConfiguration.WriteTimeout = &value
	return b
}
