/*
Copyright 2021 Kong, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/kong/kubernetes-configuration/v2/api/common/v1alpha1"
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

// KongVaultSpecApplyConfiguration represents a declarative configuration of the KongVaultSpec type for use
// with apply.
type KongVaultSpecApplyConfiguration struct {
	Backend         *string                         `json:"backend,omitempty"`
	Prefix          *string                         `json:"prefix,omitempty"`
	Description     *string                         `json:"description,omitempty"`
	Config          *v1.JSON                        `json:"config,omitempty"`
	Tags            *commonv1alpha1.Tags            `json:"tags,omitempty"`
	ControlPlaneRef *commonv1alpha1.ControlPlaneRef `json:"controlPlaneRef,omitempty"`
}

// KongVaultSpecApplyConfiguration constructs a declarative configuration of the KongVaultSpec type for use with
// apply.
func KongVaultSpec() *KongVaultSpecApplyConfiguration {
	return &KongVaultSpecApplyConfiguration{}
}

// WithBackend sets the Backend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Backend field is set to the value of the last call.
func (b *KongVaultSpecApplyConfiguration) WithBackend(value string) *KongVaultSpecApplyConfiguration {
	b.Backend = &value
	return b
}

// WithPrefix sets the Prefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prefix field is set to the value of the last call.
func (b *KongVaultSpecApplyConfiguration) WithPrefix(value string) *KongVaultSpecApplyConfiguration {
	b.Prefix = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *KongVaultSpecApplyConfiguration) WithDescription(value string) *KongVaultSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithConfig sets the Config field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Config field is set to the value of the last call.
func (b *KongVaultSpecApplyConfiguration) WithConfig(value v1.JSON) *KongVaultSpecApplyConfiguration {
	b.Config = &value
	return b
}

// WithTags sets the Tags field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tags field is set to the value of the last call.
func (b *KongVaultSpecApplyConfiguration) WithTags(value commonv1alpha1.Tags) *KongVaultSpecApplyConfiguration {
	b.Tags = &value
	return b
}

// WithControlPlaneRef sets the ControlPlaneRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ControlPlaneRef field is set to the value of the last call.
func (b *KongVaultSpecApplyConfiguration) WithControlPlaneRef(value commonv1alpha1.ControlPlaneRef) *KongVaultSpecApplyConfiguration {
	b.ControlPlaneRef = &value
	return b
}
