/*
Copyright 2021 Kong, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/kong/kubernetes-configuration/v2/api/common/v1alpha1"
)

// KongKeyAPISpecApplyConfiguration represents a declarative configuration of the KongKeyAPISpec type for use
// with apply.
type KongKeyAPISpecApplyConfiguration struct {
	KID  *string                       `json:"kid,omitempty"`
	Name *string                       `json:"name,omitempty"`
	JWK  *string                       `json:"jwk,omitempty"`
	PEM  *PEMKeyPairApplyConfiguration `json:"pem,omitempty"`
	Tags *commonv1alpha1.Tags          `json:"tags,omitempty"`
}

// KongKeyAPISpecApplyConfiguration constructs a declarative configuration of the KongKeyAPISpec type for use with
// apply.
func KongKeyAPISpec() *KongKeyAPISpecApplyConfiguration {
	return &KongKeyAPISpecApplyConfiguration{}
}

// WithKID sets the KID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KID field is set to the value of the last call.
func (b *KongKeyAPISpecApplyConfiguration) WithKID(value string) *KongKeyAPISpecApplyConfiguration {
	b.KID = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *KongKeyAPISpecApplyConfiguration) WithName(value string) *KongKeyAPISpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithJWK sets the JWK field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JWK field is set to the value of the last call.
func (b *KongKeyAPISpecApplyConfiguration) WithJWK(value string) *KongKeyAPISpecApplyConfiguration {
	b.JWK = &value
	return b
}

// WithPEM sets the PEM field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PEM field is set to the value of the last call.
func (b *KongKeyAPISpecApplyConfiguration) WithPEM(value *PEMKeyPairApplyConfiguration) *KongKeyAPISpecApplyConfiguration {
	b.PEM = value
	return b
}

// WithTags sets the Tags field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tags field is set to the value of the last call.
func (b *KongKeyAPISpecApplyConfiguration) WithTags(value commonv1alpha1.Tags) *KongKeyAPISpecApplyConfiguration {
	b.Tags = &value
	return b
}
