/*
Copyright 2021 Kong, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// KongLicenseStatusApplyConfiguration represents a declarative configuration of the KongLicenseStatus type for use
// with apply.
type KongLicenseStatusApplyConfiguration struct {
	KongLicenseControllerStatuses []KongLicenseControllerStatusApplyConfiguration `json:"controllers,omitempty"`
}

// KongLicenseStatusApplyConfiguration constructs a declarative configuration of the KongLicenseStatus type for use with
// apply.
func KongLicenseStatus() *KongLicenseStatusApplyConfiguration {
	return &KongLicenseStatusApplyConfiguration{}
}

// WithKongLicenseControllerStatuses adds the given value to the KongLicenseControllerStatuses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the KongLicenseControllerStatuses field.
func (b *KongLicenseStatusApplyConfiguration) WithKongLicenseControllerStatuses(values ...*KongLicenseControllerStatusApplyConfiguration) *KongLicenseStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithKongLicenseControllerStatuses")
		}
		b.KongLicenseControllerStatuses = append(b.KongLicenseControllerStatuses, *values[i])
	}
	return b
}
