/*
Copyright 2021 Kong, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/kong/kubernetes-configuration/v2/api/common/v1alpha1"
)

// KongCredentialBasicAuthAPISpecApplyConfiguration represents a declarative configuration of the KongCredentialBasicAuthAPISpec type for use
// with apply.
type KongCredentialBasicAuthAPISpecApplyConfiguration struct {
	Password *string              `json:"password,omitempty"`
	Tags     *commonv1alpha1.Tags `json:"tags,omitempty"`
	Username *string              `json:"username,omitempty"`
}

// KongCredentialBasicAuthAPISpecApplyConfiguration constructs a declarative configuration of the KongCredentialBasicAuthAPISpec type for use with
// apply.
func KongCredentialBasicAuthAPISpec() *KongCredentialBasicAuthAPISpecApplyConfiguration {
	return &KongCredentialBasicAuthAPISpecApplyConfiguration{}
}

// WithPassword sets the Password field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Password field is set to the value of the last call.
func (b *KongCredentialBasicAuthAPISpecApplyConfiguration) WithPassword(value string) *KongCredentialBasicAuthAPISpecApplyConfiguration {
	b.Password = &value
	return b
}

// WithTags sets the Tags field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tags field is set to the value of the last call.
func (b *KongCredentialBasicAuthAPISpecApplyConfiguration) WithTags(value commonv1alpha1.Tags) *KongCredentialBasicAuthAPISpecApplyConfiguration {
	b.Tags = &value
	return b
}

// WithUsername sets the Username field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Username field is set to the value of the last call.
func (b *KongCredentialBasicAuthAPISpecApplyConfiguration) WithUsername(value string) *KongCredentialBasicAuthAPISpecApplyConfiguration {
	b.Username = &value
	return b
}
