/*
Copyright 2021 Kong, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/kong/kubernetes-configuration/v2/api/common/v1alpha1"
)

// KongCredentialACLAPISpecApplyConfiguration represents a declarative configuration of the KongCredentialACLAPISpec type for use
// with apply.
type KongCredentialACLAPISpecApplyConfiguration struct {
	Group *string              `json:"group,omitempty"`
	Tags  *commonv1alpha1.Tags `json:"tags,omitempty"`
}

// KongCredentialACLAPISpecApplyConfiguration constructs a declarative configuration of the KongCredentialACLAPISpec type for use with
// apply.
func KongCredentialACLAPISpec() *KongCredentialACLAPISpecApplyConfiguration {
	return &KongCredentialACLAPISpecApplyConfiguration{}
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *KongCredentialACLAPISpecApplyConfiguration) WithGroup(value string) *KongCredentialACLAPISpecApplyConfiguration {
	b.Group = &value
	return b
}

// WithTags sets the Tags field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tags field is set to the value of the last call.
func (b *KongCredentialACLAPISpecApplyConfiguration) WithTags(value commonv1alpha1.Tags) *KongCredentialACLAPISpecApplyConfiguration {
	b.Tags = &value
	return b
}
