/*
Copyright 2021 Kong, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/kong/kubernetes-configuration/v2/api/common/v1alpha1"
)

// KongCredentialJWTAPISpecApplyConfiguration represents a declarative configuration of the KongCredentialJWTAPISpec type for use
// with apply.
type KongCredentialJWTAPISpecApplyConfiguration struct {
	Algorithm    *string              `json:"algorithm,omitempty"`
	ID           *string              `json:"id,omitempty"`
	Key          *string              `json:"key,omitempty"`
	RSAPublicKey *string              `json:"rsa_public_key,omitempty"`
	Secret       *string              `json:"secret,omitempty"`
	Tags         *commonv1alpha1.Tags `json:"tags,omitempty"`
}

// KongCredentialJWTAPISpecApplyConfiguration constructs a declarative configuration of the KongCredentialJWTAPISpec type for use with
// apply.
func KongCredentialJWTAPISpec() *KongCredentialJWTAPISpecApplyConfiguration {
	return &KongCredentialJWTAPISpecApplyConfiguration{}
}

// WithAlgorithm sets the Algorithm field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Algorithm field is set to the value of the last call.
func (b *KongCredentialJWTAPISpecApplyConfiguration) WithAlgorithm(value string) *KongCredentialJWTAPISpecApplyConfiguration {
	b.Algorithm = &value
	return b
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *KongCredentialJWTAPISpecApplyConfiguration) WithID(value string) *KongCredentialJWTAPISpecApplyConfiguration {
	b.ID = &value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *KongCredentialJWTAPISpecApplyConfiguration) WithKey(value string) *KongCredentialJWTAPISpecApplyConfiguration {
	b.Key = &value
	return b
}

// WithRSAPublicKey sets the RSAPublicKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RSAPublicKey field is set to the value of the last call.
func (b *KongCredentialJWTAPISpecApplyConfiguration) WithRSAPublicKey(value string) *KongCredentialJWTAPISpecApplyConfiguration {
	b.RSAPublicKey = &value
	return b
}

// WithSecret sets the Secret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Secret field is set to the value of the last call.
func (b *KongCredentialJWTAPISpecApplyConfiguration) WithSecret(value string) *KongCredentialJWTAPISpecApplyConfiguration {
	b.Secret = &value
	return b
}

// WithTags sets the Tags field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tags field is set to the value of the last call.
func (b *KongCredentialJWTAPISpecApplyConfiguration) WithTags(value commonv1alpha1.Tags) *KongCredentialJWTAPISpecApplyConfiguration {
	b.Tags = &value
	return b
}
