/*
Copyright 2021 Kong, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/kong/kubernetes-configuration/v2/api/common/v1alpha1"
	v1 "k8s.io/api/core/v1"
)

// KongCredentialAPIKeySpecApplyConfiguration represents a declarative configuration of the KongCredentialAPIKeySpec type for use
// with apply.
type KongCredentialAPIKeySpecApplyConfiguration struct {
	ConsumerRef                                   *v1.LocalObjectReference `json:"consumerRef,omitempty"`
	KongCredentialAPIKeyAPISpecApplyConfiguration `json:",inline"`
}

// KongCredentialAPIKeySpecApplyConfiguration constructs a declarative configuration of the KongCredentialAPIKeySpec type for use with
// apply.
func KongCredentialAPIKeySpec() *KongCredentialAPIKeySpecApplyConfiguration {
	return &KongCredentialAPIKeySpecApplyConfiguration{}
}

// WithConsumerRef sets the ConsumerRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConsumerRef field is set to the value of the last call.
func (b *KongCredentialAPIKeySpecApplyConfiguration) WithConsumerRef(value v1.LocalObjectReference) *KongCredentialAPIKeySpecApplyConfiguration {
	b.ConsumerRef = &value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *KongCredentialAPIKeySpecApplyConfiguration) WithKey(value string) *KongCredentialAPIKeySpecApplyConfiguration {
	b.KongCredentialAPIKeyAPISpecApplyConfiguration.Key = &value
	return b
}

// WithTags sets the Tags field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tags field is set to the value of the last call.
func (b *KongCredentialAPIKeySpecApplyConfiguration) WithTags(value commonv1alpha1.Tags) *KongCredentialAPIKeySpecApplyConfiguration {
	b.KongCredentialAPIKeyAPISpecApplyConfiguration.Tags = &value
	return b
}
