/*
Copyright 2021 Kong, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PEMKeyPairApplyConfiguration represents a declarative configuration of the PEMKeyPair type for use
// with apply.
type PEMKeyPairApplyConfiguration struct {
	PrivateKey *string `json:"private_key,omitempty"`
	PublicKey  *string `json:"public_key,omitempty"`
}

// PEMKeyPairApplyConfiguration constructs a declarative configuration of the PEMKeyPair type for use with
// apply.
func PEMKeyPair() *PEMKeyPairApplyConfiguration {
	return &PEMKeyPairApplyConfiguration{}
}

// WithPrivateKey sets the PrivateKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrivateKey field is set to the value of the last call.
func (b *PEMKeyPairApplyConfiguration) WithPrivateKey(value string) *PEMKeyPairApplyConfiguration {
	b.PrivateKey = &value
	return b
}

// WithPublicKey sets the PublicKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PublicKey field is set to the value of the last call.
func (b *PEMKeyPairApplyConfiguration) WithPublicKey(value string) *PEMKeyPairApplyConfiguration {
	b.PublicKey = &value
	return b
}
