/*
Copyright 2021 Kong, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/kong/kubernetes-configuration/api/configuration/v1alpha1"
	scheme "github.com/kong/kubernetes-configuration/pkg/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// KongCertificatesGetter has a method to return a KongCertificateInterface.
// A group's client should implement this interface.
type KongCertificatesGetter interface {
	KongCertificates(namespace string) KongCertificateInterface
}

// KongCertificateInterface has methods to work with KongCertificate resources.
type KongCertificateInterface interface {
	Create(ctx context.Context, kongCertificate *v1alpha1.KongCertificate, opts v1.CreateOptions) (*v1alpha1.KongCertificate, error)
	Update(ctx context.Context, kongCertificate *v1alpha1.KongCertificate, opts v1.UpdateOptions) (*v1alpha1.KongCertificate, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, kongCertificate *v1alpha1.KongCertificate, opts v1.UpdateOptions) (*v1alpha1.KongCertificate, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.KongCertificate, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.KongCertificateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KongCertificate, err error)
	KongCertificateExpansion
}

// kongCertificates implements KongCertificateInterface
type kongCertificates struct {
	*gentype.ClientWithList[*v1alpha1.KongCertificate, *v1alpha1.KongCertificateList]
}

// newKongCertificates returns a KongCertificates
func newKongCertificates(c *ConfigurationV1alpha1Client, namespace string) *kongCertificates {
	return &kongCertificates{
		gentype.NewClientWithList[*v1alpha1.KongCertificate, *v1alpha1.KongCertificateList](
			"kongcertificates",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.KongCertificate { return &v1alpha1.KongCertificate{} },
			func() *v1alpha1.KongCertificateList { return &v1alpha1.KongCertificateList{} }),
	}
}
