apiVersion: gateway-operator.konghq.com/v2alpha1
kind: ControlPlane
metadata:
  name: controlplane-v2-example
spec:
  ingressClass: kong
  dataplane:
    type: ref
    ref:
      name: dataplane-name
  translation:
    drainSupport: enabled
