kind: GatewayConfiguration
apiVersion: gateway-operator.konghq.com/v2alpha1
metadata:
  name: kong
  namespace: default
spec:
  dataPlaneOptions:
    resources:
      podDisruptionBudget:
        spec:
          maxUnavailable: 1
    deployment:
      replicas: 2
      podTemplateSpec:
        metadata:
          labels:
            dataplane-pod-label: example
          annotations:
            dataplane-pod-annotation: example
        spec:
          containers:
          - name: proxy
            # renovate: datasource=docker versioning=docker
            image: kong/kong-gateway:3.10
            readinessProbe:
              initialDelaySeconds: 1
              periodSeconds: 1
  controlPlaneOptions:
    gatewayDiscovery:
      readinessCheckInterval: 15s
      readinessCheckTimeout: 10s

