apiVersion: configuration.konghq.com/v1alpha1
kind: KongPluginBinding
metadata:
  generation: 1
  name: targeted-binding
spec:
  pluginRef:
    name: plugin-sample
  targets:
    consumerRef:
      name: consumer-sample
    serviceRef:
      name: service-sample
      kind: KongService
      group: configuration.konghq.com
    routeRef:
      name: route-sample
      kind: KongRoute
      group: configuration.konghq.com
---
apiVersion: configuration.konghq.com/v1alpha1
kind: KongPluginBinding
metadata:
  generation: 1
  name: global-binding
spec:
  pluginRef:
    name: plugin-sample
  global: true
