kind: KonnectAPIAuthConfiguration
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: konnect-api-auth-1
spec:
  type: token
  token: kpat_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  serverURL: eu.api.konghq.com
---
apiVersion: konnect.konghq.com/v1alpha1
kind: KonnectNetwork
metadata:
  name: network1
spec:
  name: network1
  cloud_gateway_provider_account_id: "1234"
  availability_zones:
  - us-west-1
  cidr_block: "10.0.0.1/24"
  region: us-west
  # NOTE: this is required as of now because we embded the sdk type in the CRD
  # and we do not have controler over the field being optional or required
  # without any additional machinery in place.
  # The API itself https://docs.konghq.com/konnect/api/cloud-gateways/latest/#/Networks/create-network
  # does not require this field.
  state: initializing
  konnect:
    authRef:
      name: konnect-api-auth-1

