/*
Copyright 2021 Kong, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kong/kubernetes-configuration/api/configuration/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCredentialBasicAuths implements CredentialBasicAuthInterface
type FakeCredentialBasicAuths struct {
	Fake *FakeConfigurationV1alpha1
	ns   string
}

var credentialbasicauthsResource = v1alpha1.SchemeGroupVersion.WithResource("credentialbasicauths")

var credentialbasicauthsKind = v1alpha1.SchemeGroupVersion.WithKind("CredentialBasicAuth")

// Get takes name of the credentialBasicAuth, and returns the corresponding credentialBasicAuth object, and an error if there is any.
func (c *FakeCredentialBasicAuths) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CredentialBasicAuth, err error) {
	emptyResult := &v1alpha1.CredentialBasicAuth{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(credentialbasicauthsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.CredentialBasicAuth), err
}

// List takes label and field selectors, and returns the list of CredentialBasicAuths that match those selectors.
func (c *FakeCredentialBasicAuths) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CredentialBasicAuthList, err error) {
	emptyResult := &v1alpha1.CredentialBasicAuthList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(credentialbasicauthsResource, credentialbasicauthsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CredentialBasicAuthList{ListMeta: obj.(*v1alpha1.CredentialBasicAuthList).ListMeta}
	for _, item := range obj.(*v1alpha1.CredentialBasicAuthList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested credentialBasicAuths.
func (c *FakeCredentialBasicAuths) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(credentialbasicauthsResource, c.ns, opts))

}

// Create takes the representation of a credentialBasicAuth and creates it.  Returns the server's representation of the credentialBasicAuth, and an error, if there is any.
func (c *FakeCredentialBasicAuths) Create(ctx context.Context, credentialBasicAuth *v1alpha1.CredentialBasicAuth, opts v1.CreateOptions) (result *v1alpha1.CredentialBasicAuth, err error) {
	emptyResult := &v1alpha1.CredentialBasicAuth{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(credentialbasicauthsResource, c.ns, credentialBasicAuth, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.CredentialBasicAuth), err
}

// Update takes the representation of a credentialBasicAuth and updates it. Returns the server's representation of the credentialBasicAuth, and an error, if there is any.
func (c *FakeCredentialBasicAuths) Update(ctx context.Context, credentialBasicAuth *v1alpha1.CredentialBasicAuth, opts v1.UpdateOptions) (result *v1alpha1.CredentialBasicAuth, err error) {
	emptyResult := &v1alpha1.CredentialBasicAuth{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(credentialbasicauthsResource, c.ns, credentialBasicAuth, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.CredentialBasicAuth), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCredentialBasicAuths) UpdateStatus(ctx context.Context, credentialBasicAuth *v1alpha1.CredentialBasicAuth, opts v1.UpdateOptions) (result *v1alpha1.CredentialBasicAuth, err error) {
	emptyResult := &v1alpha1.CredentialBasicAuth{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(credentialbasicauthsResource, "status", c.ns, credentialBasicAuth, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.CredentialBasicAuth), err
}

// Delete takes name of the credentialBasicAuth and deletes it. Returns an error if one occurs.
func (c *FakeCredentialBasicAuths) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(credentialbasicauthsResource, c.ns, name, opts), &v1alpha1.CredentialBasicAuth{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCredentialBasicAuths) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(credentialbasicauthsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CredentialBasicAuthList{})
	return err
}

// Patch applies the patch and returns the patched credentialBasicAuth.
func (c *FakeCredentialBasicAuths) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CredentialBasicAuth, err error) {
	emptyResult := &v1alpha1.CredentialBasicAuth{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(credentialbasicauthsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.CredentialBasicAuth), err
}
