/*
Copyright 2021 Kong, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kong/kubernetes-configuration/api/configuration/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKongCertificates implements KongCertificateInterface
type FakeKongCertificates struct {
	Fake *FakeConfigurationV1alpha1
	ns   string
}

var kongcertificatesResource = v1alpha1.SchemeGroupVersion.WithResource("kongcertificates")

var kongcertificatesKind = v1alpha1.SchemeGroupVersion.WithKind("KongCertificate")

// Get takes name of the kongCertificate, and returns the corresponding kongCertificate object, and an error if there is any.
func (c *FakeKongCertificates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KongCertificate, err error) {
	emptyResult := &v1alpha1.KongCertificate{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(kongcertificatesResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongCertificate), err
}

// List takes label and field selectors, and returns the list of KongCertificates that match those selectors.
func (c *FakeKongCertificates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KongCertificateList, err error) {
	emptyResult := &v1alpha1.KongCertificateList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(kongcertificatesResource, kongcertificatesKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KongCertificateList{ListMeta: obj.(*v1alpha1.KongCertificateList).ListMeta}
	for _, item := range obj.(*v1alpha1.KongCertificateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kongCertificates.
func (c *FakeKongCertificates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(kongcertificatesResource, c.ns, opts))

}

// Create takes the representation of a kongCertificate and creates it.  Returns the server's representation of the kongCertificate, and an error, if there is any.
func (c *FakeKongCertificates) Create(ctx context.Context, kongCertificate *v1alpha1.KongCertificate, opts v1.CreateOptions) (result *v1alpha1.KongCertificate, err error) {
	emptyResult := &v1alpha1.KongCertificate{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(kongcertificatesResource, c.ns, kongCertificate, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongCertificate), err
}

// Update takes the representation of a kongCertificate and updates it. Returns the server's representation of the kongCertificate, and an error, if there is any.
func (c *FakeKongCertificates) Update(ctx context.Context, kongCertificate *v1alpha1.KongCertificate, opts v1.UpdateOptions) (result *v1alpha1.KongCertificate, err error) {
	emptyResult := &v1alpha1.KongCertificate{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(kongcertificatesResource, c.ns, kongCertificate, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongCertificate), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKongCertificates) UpdateStatus(ctx context.Context, kongCertificate *v1alpha1.KongCertificate, opts v1.UpdateOptions) (result *v1alpha1.KongCertificate, err error) {
	emptyResult := &v1alpha1.KongCertificate{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(kongcertificatesResource, "status", c.ns, kongCertificate, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongCertificate), err
}

// Delete takes name of the kongCertificate and deletes it. Returns an error if one occurs.
func (c *FakeKongCertificates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(kongcertificatesResource, c.ns, name, opts), &v1alpha1.KongCertificate{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKongCertificates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(kongcertificatesResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KongCertificateList{})
	return err
}

// Patch applies the patch and returns the patched kongCertificate.
func (c *FakeKongCertificates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KongCertificate, err error) {
	emptyResult := &v1alpha1.KongCertificate{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(kongcertificatesResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongCertificate), err
}
