/*
Copyright 2021 Kong, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kong/kubernetes-configuration/api/configuration/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKongDataplaneCertificates implements KongDataplaneCertificateInterface
type FakeKongDataplaneCertificates struct {
	Fake *FakeConfigurationV1alpha1
	ns   string
}

var kongdataplanecertificatesResource = v1alpha1.SchemeGroupVersion.WithResource("kongdataplanecertificates")

var kongdataplanecertificatesKind = v1alpha1.SchemeGroupVersion.WithKind("KongDataplaneCertificate")

// Get takes name of the kongDataplaneCertificate, and returns the corresponding kongDataplaneCertificate object, and an error if there is any.
func (c *FakeKongDataplaneCertificates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KongDataplaneCertificate, err error) {
	emptyResult := &v1alpha1.KongDataplaneCertificate{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(kongdataplanecertificatesResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongDataplaneCertificate), err
}

// List takes label and field selectors, and returns the list of KongDataplaneCertificates that match those selectors.
func (c *FakeKongDataplaneCertificates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KongDataplaneCertificateList, err error) {
	emptyResult := &v1alpha1.KongDataplaneCertificateList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(kongdataplanecertificatesResource, kongdataplanecertificatesKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KongDataplaneCertificateList{ListMeta: obj.(*v1alpha1.KongDataplaneCertificateList).ListMeta}
	for _, item := range obj.(*v1alpha1.KongDataplaneCertificateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kongDataplaneCertificates.
func (c *FakeKongDataplaneCertificates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(kongdataplanecertificatesResource, c.ns, opts))

}

// Create takes the representation of a kongDataplaneCertificate and creates it.  Returns the server's representation of the kongDataplaneCertificate, and an error, if there is any.
func (c *FakeKongDataplaneCertificates) Create(ctx context.Context, kongDataplaneCertificate *v1alpha1.KongDataplaneCertificate, opts v1.CreateOptions) (result *v1alpha1.KongDataplaneCertificate, err error) {
	emptyResult := &v1alpha1.KongDataplaneCertificate{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(kongdataplanecertificatesResource, c.ns, kongDataplaneCertificate, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongDataplaneCertificate), err
}

// Update takes the representation of a kongDataplaneCertificate and updates it. Returns the server's representation of the kongDataplaneCertificate, and an error, if there is any.
func (c *FakeKongDataplaneCertificates) Update(ctx context.Context, kongDataplaneCertificate *v1alpha1.KongDataplaneCertificate, opts v1.UpdateOptions) (result *v1alpha1.KongDataplaneCertificate, err error) {
	emptyResult := &v1alpha1.KongDataplaneCertificate{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(kongdataplanecertificatesResource, c.ns, kongDataplaneCertificate, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongDataplaneCertificate), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKongDataplaneCertificates) UpdateStatus(ctx context.Context, kongDataplaneCertificate *v1alpha1.KongDataplaneCertificate, opts v1.UpdateOptions) (result *v1alpha1.KongDataplaneCertificate, err error) {
	emptyResult := &v1alpha1.KongDataplaneCertificate{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(kongdataplanecertificatesResource, "status", c.ns, kongDataplaneCertificate, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongDataplaneCertificate), err
}

// Delete takes name of the kongDataplaneCertificate and deletes it. Returns an error if one occurs.
func (c *FakeKongDataplaneCertificates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(kongdataplanecertificatesResource, c.ns, name, opts), &v1alpha1.KongDataplaneCertificate{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKongDataplaneCertificates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(kongdataplanecertificatesResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KongDataplaneCertificateList{})
	return err
}

// Patch applies the patch and returns the patched kongDataplaneCertificate.
func (c *FakeKongDataplaneCertificates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KongDataplaneCertificate, err error) {
	emptyResult := &v1alpha1.KongDataplaneCertificate{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(kongdataplanecertificatesResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongDataplaneCertificate), err
}
