/*
Copyright 2021 Kong, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kong/kubernetes-configuration/api/configuration/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKongCACertificates implements KongCACertificateInterface
type FakeKongCACertificates struct {
	Fake *FakeConfigurationV1alpha1
	ns   string
}

var kongcacertificatesResource = v1alpha1.SchemeGroupVersion.WithResource("kongcacertificates")

var kongcacertificatesKind = v1alpha1.SchemeGroupVersion.WithKind("KongCACertificate")

// Get takes name of the kongCACertificate, and returns the corresponding kongCACertificate object, and an error if there is any.
func (c *FakeKongCACertificates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KongCACertificate, err error) {
	emptyResult := &v1alpha1.KongCACertificate{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(kongcacertificatesResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongCACertificate), err
}

// List takes label and field selectors, and returns the list of KongCACertificates that match those selectors.
func (c *FakeKongCACertificates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KongCACertificateList, err error) {
	emptyResult := &v1alpha1.KongCACertificateList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(kongcacertificatesResource, kongcacertificatesKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KongCACertificateList{ListMeta: obj.(*v1alpha1.KongCACertificateList).ListMeta}
	for _, item := range obj.(*v1alpha1.KongCACertificateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kongCACertificates.
func (c *FakeKongCACertificates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(kongcacertificatesResource, c.ns, opts))

}

// Create takes the representation of a kongCACertificate and creates it.  Returns the server's representation of the kongCACertificate, and an error, if there is any.
func (c *FakeKongCACertificates) Create(ctx context.Context, kongCACertificate *v1alpha1.KongCACertificate, opts v1.CreateOptions) (result *v1alpha1.KongCACertificate, err error) {
	emptyResult := &v1alpha1.KongCACertificate{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(kongcacertificatesResource, c.ns, kongCACertificate, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongCACertificate), err
}

// Update takes the representation of a kongCACertificate and updates it. Returns the server's representation of the kongCACertificate, and an error, if there is any.
func (c *FakeKongCACertificates) Update(ctx context.Context, kongCACertificate *v1alpha1.KongCACertificate, opts v1.UpdateOptions) (result *v1alpha1.KongCACertificate, err error) {
	emptyResult := &v1alpha1.KongCACertificate{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(kongcacertificatesResource, c.ns, kongCACertificate, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongCACertificate), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKongCACertificates) UpdateStatus(ctx context.Context, kongCACertificate *v1alpha1.KongCACertificate, opts v1.UpdateOptions) (result *v1alpha1.KongCACertificate, err error) {
	emptyResult := &v1alpha1.KongCACertificate{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(kongcacertificatesResource, "status", c.ns, kongCACertificate, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongCACertificate), err
}

// Delete takes name of the kongCACertificate and deletes it. Returns an error if one occurs.
func (c *FakeKongCACertificates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(kongcacertificatesResource, c.ns, name, opts), &v1alpha1.KongCACertificate{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKongCACertificates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(kongcacertificatesResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KongCACertificateList{})
	return err
}

// Patch applies the patch and returns the patched kongCACertificate.
func (c *FakeKongCACertificates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KongCACertificate, err error) {
	emptyResult := &v1alpha1.KongCACertificate{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(kongcacertificatesResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongCACertificate), err
}
