/*
Copyright 2021 Kong, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kong/kubernetes-configuration/api/configuration/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKongUpstreams implements KongUpstreamInterface
type FakeKongUpstreams struct {
	Fake *FakeConfigurationV1alpha1
	ns   string
}

var kongupstreamsResource = v1alpha1.SchemeGroupVersion.WithResource("kongupstreams")

var kongupstreamsKind = v1alpha1.SchemeGroupVersion.WithKind("KongUpstream")

// Get takes name of the kongUpstream, and returns the corresponding kongUpstream object, and an error if there is any.
func (c *FakeKongUpstreams) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KongUpstream, err error) {
	emptyResult := &v1alpha1.KongUpstream{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(kongupstreamsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongUpstream), err
}

// List takes label and field selectors, and returns the list of KongUpstreams that match those selectors.
func (c *FakeKongUpstreams) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KongUpstreamList, err error) {
	emptyResult := &v1alpha1.KongUpstreamList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(kongupstreamsResource, kongupstreamsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KongUpstreamList{ListMeta: obj.(*v1alpha1.KongUpstreamList).ListMeta}
	for _, item := range obj.(*v1alpha1.KongUpstreamList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kongUpstreams.
func (c *FakeKongUpstreams) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(kongupstreamsResource, c.ns, opts))

}

// Create takes the representation of a kongUpstream and creates it.  Returns the server's representation of the kongUpstream, and an error, if there is any.
func (c *FakeKongUpstreams) Create(ctx context.Context, kongUpstream *v1alpha1.KongUpstream, opts v1.CreateOptions) (result *v1alpha1.KongUpstream, err error) {
	emptyResult := &v1alpha1.KongUpstream{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(kongupstreamsResource, c.ns, kongUpstream, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongUpstream), err
}

// Update takes the representation of a kongUpstream and updates it. Returns the server's representation of the kongUpstream, and an error, if there is any.
func (c *FakeKongUpstreams) Update(ctx context.Context, kongUpstream *v1alpha1.KongUpstream, opts v1.UpdateOptions) (result *v1alpha1.KongUpstream, err error) {
	emptyResult := &v1alpha1.KongUpstream{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(kongupstreamsResource, c.ns, kongUpstream, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongUpstream), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKongUpstreams) UpdateStatus(ctx context.Context, kongUpstream *v1alpha1.KongUpstream, opts v1.UpdateOptions) (result *v1alpha1.KongUpstream, err error) {
	emptyResult := &v1alpha1.KongUpstream{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(kongupstreamsResource, "status", c.ns, kongUpstream, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongUpstream), err
}

// Delete takes name of the kongUpstream and deletes it. Returns an error if one occurs.
func (c *FakeKongUpstreams) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(kongupstreamsResource, c.ns, name, opts), &v1alpha1.KongUpstream{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKongUpstreams) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(kongupstreamsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KongUpstreamList{})
	return err
}

// Patch applies the patch and returns the patched kongUpstream.
func (c *FakeKongUpstreams) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KongUpstream, err error) {
	emptyResult := &v1alpha1.KongUpstream{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(kongupstreamsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongUpstream), err
}
