/*
Copyright 2021 Kong, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kong/kubernetes-configuration/api/configuration/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKongServices implements KongServiceInterface
type FakeKongServices struct {
	Fake *FakeConfigurationV1alpha1
	ns   string
}

var kongservicesResource = v1alpha1.SchemeGroupVersion.WithResource("kongservices")

var kongservicesKind = v1alpha1.SchemeGroupVersion.WithKind("KongService")

// Get takes name of the kongService, and returns the corresponding kongService object, and an error if there is any.
func (c *FakeKongServices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KongService, err error) {
	emptyResult := &v1alpha1.KongService{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(kongservicesResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongService), err
}

// List takes label and field selectors, and returns the list of KongServices that match those selectors.
func (c *FakeKongServices) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KongServiceList, err error) {
	emptyResult := &v1alpha1.KongServiceList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(kongservicesResource, kongservicesKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KongServiceList{ListMeta: obj.(*v1alpha1.KongServiceList).ListMeta}
	for _, item := range obj.(*v1alpha1.KongServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kongServices.
func (c *FakeKongServices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(kongservicesResource, c.ns, opts))

}

// Create takes the representation of a kongService and creates it.  Returns the server's representation of the kongService, and an error, if there is any.
func (c *FakeKongServices) Create(ctx context.Context, kongService *v1alpha1.KongService, opts v1.CreateOptions) (result *v1alpha1.KongService, err error) {
	emptyResult := &v1alpha1.KongService{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(kongservicesResource, c.ns, kongService, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongService), err
}

// Update takes the representation of a kongService and updates it. Returns the server's representation of the kongService, and an error, if there is any.
func (c *FakeKongServices) Update(ctx context.Context, kongService *v1alpha1.KongService, opts v1.UpdateOptions) (result *v1alpha1.KongService, err error) {
	emptyResult := &v1alpha1.KongService{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(kongservicesResource, c.ns, kongService, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongService), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKongServices) UpdateStatus(ctx context.Context, kongService *v1alpha1.KongService, opts v1.UpdateOptions) (result *v1alpha1.KongService, err error) {
	emptyResult := &v1alpha1.KongService{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(kongservicesResource, "status", c.ns, kongService, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongService), err
}

// Delete takes name of the kongService and deletes it. Returns an error if one occurs.
func (c *FakeKongServices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(kongservicesResource, c.ns, name, opts), &v1alpha1.KongService{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKongServices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(kongservicesResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KongServiceList{})
	return err
}

// Patch applies the patch and returns the patched kongService.
func (c *FakeKongServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KongService, err error) {
	emptyResult := &v1alpha1.KongService{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(kongservicesResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongService), err
}
