/*
Copyright 2021 Kong, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kong/kubernetes-configuration/api/configuration/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKongRoutes implements KongRouteInterface
type FakeKongRoutes struct {
	Fake *FakeConfigurationV1alpha1
	ns   string
}

var kongroutesResource = v1alpha1.SchemeGroupVersion.WithResource("kongroutes")

var kongroutesKind = v1alpha1.SchemeGroupVersion.WithKind("KongRoute")

// Get takes name of the kongRoute, and returns the corresponding kongRoute object, and an error if there is any.
func (c *FakeKongRoutes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KongRoute, err error) {
	emptyResult := &v1alpha1.KongRoute{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(kongroutesResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongRoute), err
}

// List takes label and field selectors, and returns the list of KongRoutes that match those selectors.
func (c *FakeKongRoutes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KongRouteList, err error) {
	emptyResult := &v1alpha1.KongRouteList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(kongroutesResource, kongroutesKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KongRouteList{ListMeta: obj.(*v1alpha1.KongRouteList).ListMeta}
	for _, item := range obj.(*v1alpha1.KongRouteList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kongRoutes.
func (c *FakeKongRoutes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(kongroutesResource, c.ns, opts))

}

// Create takes the representation of a kongRoute and creates it.  Returns the server's representation of the kongRoute, and an error, if there is any.
func (c *FakeKongRoutes) Create(ctx context.Context, kongRoute *v1alpha1.KongRoute, opts v1.CreateOptions) (result *v1alpha1.KongRoute, err error) {
	emptyResult := &v1alpha1.KongRoute{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(kongroutesResource, c.ns, kongRoute, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongRoute), err
}

// Update takes the representation of a kongRoute and updates it. Returns the server's representation of the kongRoute, and an error, if there is any.
func (c *FakeKongRoutes) Update(ctx context.Context, kongRoute *v1alpha1.KongRoute, opts v1.UpdateOptions) (result *v1alpha1.KongRoute, err error) {
	emptyResult := &v1alpha1.KongRoute{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(kongroutesResource, c.ns, kongRoute, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongRoute), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKongRoutes) UpdateStatus(ctx context.Context, kongRoute *v1alpha1.KongRoute, opts v1.UpdateOptions) (result *v1alpha1.KongRoute, err error) {
	emptyResult := &v1alpha1.KongRoute{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(kongroutesResource, "status", c.ns, kongRoute, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongRoute), err
}

// Delete takes name of the kongRoute and deletes it. Returns an error if one occurs.
func (c *FakeKongRoutes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(kongroutesResource, c.ns, name, opts), &v1alpha1.KongRoute{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKongRoutes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(kongroutesResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KongRouteList{})
	return err
}

// Patch applies the patch and returns the patched kongRoute.
func (c *FakeKongRoutes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KongRoute, err error) {
	emptyResult := &v1alpha1.KongRoute{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(kongroutesResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.KongRoute), err
}
